#!/usr/bin/env python3
"""
generate_fixes.py — Generate per-exam fix scripts from the audit report.

For each c-value mismatch with high confidence (sim >= 0.90) and
single-accepted answer, output a ready-to-apply fix script.

The generated scripts follow the same pattern as the existing
scripts/sept24_basis_fix.py (manually-verified template).
"""
import json, sys
from pathlib import Path

HERE = Path(__file__).parent
REPORTS = HERE / 'reports'
OUTPUT = HERE / 'generated_fixes'
OUTPUT.mkdir(exist_ok=True)

def render_fix_script(exam_id, c_mismatches, track, date, answer_source='revised'):
    """Render a Python fix script that applies the verified c-value corrections."""
    # Only include high-confidence single-accept fixes
    fixes = []
    for m in c_mismatches:
        if m['sim'] < 0.90:
            continue
        if len(m['accepted']) != 1:
            continue  # Multi-accept; current c may already be in accepted — double-check
        fixes.append(m)
    
    if not fixes:
        return None
    
    lines = [
        '#!/usr/bin/env python3',
        f'"""',
        f'{exam_id}_fix.py — Apply c-value fixes for {exam_id}.',
        '',
        f'Exam: {exam_id} ({track} / {date})',
        f'Answer source: IMA {answer_source} answer key',
        f'Confidence: sim >= 0.90, single accepted answer.',
        '',
        'Generated by scripts/exam_audit/generate_fixes.py from audit report.',
        '',
        'Usage:',
        '    python3 {}_fix.py              # dry run'.format(exam_id),
        '    python3 {}_fix.py --apply      # write changes to questions.json'.format(exam_id),
        '"""',
        'import json, sys',
        'from pathlib import Path',
        '',
        'REPO = Path(__file__).resolve().parent.parent.parent.parent',
        "QJ = REPO / 'data' / 'questions.json'",
        '',
        '# Each entry: (q_num, idx, new_c, accepted_list, current_tag, similarity)',
        'FIXES = [',
    ]
    for m in fixes:
        lines.append(f'    ({m["q_num"]:3d}, {m["idx"]:5d}, {m["recommended_c"]}, {m["accepted"]}, {m["tag"]!r}, {m["sim"]}),')
    lines += [
        ']',
        '',
        'def main():',
        "    apply = '--apply' in sys.argv",
        '    with open(QJ) as f: qs = json.load(f)',
        '    changed = 0',
        '    for q_num, idx, new_c, accepted, cur_tag, sim in FIXES:',
        '        q = qs[idx]',
        "        cur_c = q.get('c')",
        '        if cur_c in accepted:',
        '            continue  # already valid',
        "        print(f'  Q{q_num}: idx={idx} tag={cur_tag!r} c={cur_c} → {new_c} (sim {sim})')",
        '        if apply:',
        "            qs[idx]['c'] = new_c",
        '            changed += 1',
        "    print(f'\\nTotal fixes in script: {len(FIXES)}')",
        '    if apply:',
        "        print(f'Applied: {changed}')",
        "        with open(QJ, 'w') as f: json.dump(qs, f, ensure_ascii=False, indent=1)",
        '    else:',
        "        print('DRY RUN — use --apply to write changes')",
        '',
        "if __name__ == '__main__':",
        '    main()',
    ]
    return '\n'.join(lines) + '\n'

def main():
    with open(HERE / 'sources.json') as f:
        src = json.load(f)
    
    exam_map = {e['id']: e for e in src['exams']}
    
    reports = json.load(open(REPORTS / '_all_reports.json'))
    
    summary = []
    for exam_id, r in reports.items():
        exam = exam_map[exam_id]
        c_mis = r['findings']['c_mismatches']
        if not c_mis:
            continue
        script = render_fix_script(exam_id, c_mis, exam['track'], exam['date'])
        if script:
            path = OUTPUT / f'{exam_id}_fix.py'
            path.write_text(script)
            hc_count = sum(1 for m in c_mis if m['sim'] >= 0.90 and len(m['accepted']) == 1)
            summary.append((exam_id, len(c_mis), hc_count, str(path)))
            print(f'  Generated: {path} ({hc_count} high-confidence fixes of {len(c_mis)} total)')
    
    print(f'\n{len(summary)} fix scripts generated in {OUTPUT}/')
    print(f'\nTotal high-confidence c-value fixes across all exams: {sum(s[2] for s in summary)}')

if __name__ == '__main__':
    main()
